before_script:
  - export PATH=/opt/android-sdk-linux/sdk/platform-tools:$PATH
  - echo "$USER"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

.base:
  before_script:
   - pwd
  tags:
   - android

jobBuild :
   stage: build
   extends: .base
   script:
    - ./gradlew clean lint assembleDebug

